#!/bin/sh

export CLASSPATH="classes:lib/jep-2.3.0.jar:lib/djep-1.0.0.jar:lib/jung-algorithms-2.0.1.jar:lib/jung-api-2.0.1.jar:lib/jung-graph-impl-2.0.1.jar:lib/jung-io-2.0.1.jar:lib/jung-visualization-2.0.1.jar:lib/jfreechart-1.0.12.jar:lib/jcommon-1.0.15.jar:lib/guava-r09-rc1.jar:lib/commons-math3-3.1.jar"
#export CLASSPATH="classes:lib/commons-logging-1.1.jar:lib/ws-commons-util-1.0.2.jar:lib/xmlrpc-common-3.1.3.jar:lib/xmlrpc-client-3.1.3.jar:lib/jep-2.3.0.jar:lib/djep-1.0.0.jar:lib/jung-algorithms-2.0.1.jar:lib/jung-api-2.0.1.jar:lib/jung-graph-impl-2.0.1.jar:lib/jung-io-2.0.1.jar:lib/jung-visualization-2.0.1.jar:lib/jfreechart-1.0.12.jar:lib/jcommon-1.0.15.jar:lib/guava-r09-rc1.jar:lib/commons-math3-3.1.jar"

java -Xmx2500M peersim.Simulator $1
